#!/usr/bin/perl -w


# this one scales offsets, then scales all the outputs

# open the files

open(DATA, "cycles_data");
@data = <DATA>;
close(DATA);

open(OUTPUT, "> processed_cycles_data");

# put them in order
@titles = split(' ', $data[0]);
print OUTPUT $data[0];
shift @data; # take off the titles
shift @titles; # take off do nothing


foreach $line (@data)
{
	$line =~ /([0-9]*) ([0-9]*) (.*)/;
	print OUTPUT "$1 ";

	@results = split(' ', $3);

	for($i = 0; $i < scalar(@titles); $i++)
	{
		if ($results[$i] == 0)
		{
			print OUTPUT "0 ";
		}
		else
		{
			print OUTPUT "".($results[$i] - $2) / $1." ";
		}
	}
	print OUTPUT "\n";
}

close(OUTPUT);
