#!/bin/sh

for ((  i = 0 ;  i < 190;  i++  ))
do
# do the faster sorts first
	for j in base_quicksort base_quicksort9 cache_quicksort multi_quicksort multi_quicksort_seq 
	do
		for k in 4096 8192 16384 32768 65536 131072 262144 524288 1048576 2097152 4194304
		do
			do_perfex $j $i $k
		done
	done 

# now do the on^2 sorts
done
