#!/bin/bash

simple -c "$1" do_nothing

simple -c "$1" -M 32768 on2_insertsort
simple -c "$1" -M 32768 on2_selectsort
simple -c "$1" -M 32768 on2_bubblesort
simple -c "$1" -M 32768 on2_shakersort

simple -c "$1" base_heapsort
simple -c "$1" cache_heapsort
simple -c "$1" cache4_heapsort
simple -c "$1" -L 16 cache4_heapsort

simple -c "$1" base_quicksort
simple -c "$1" cache_quicksort
simple -c "$1" multi_quicksort
simple -c "$1" multi_quicksort_seq

simple -c "$1" base_radixsort

simple -c "$1" base_mergesort
simple -c "$1" knuth_base_mergesort
simple -c "$1" knuth_other_base_mergesort
simple -c "$1" tiled_mergesort
simple -c "$1" double_tiled_mergesort
simple -c "$1" multi_mergesort
simple -c "$1" double_multi_mergesort


