#!/bin/bash

#simple -c "random.org" do_nothing

#simple -c "extra" -m 65536 -M 65536 on2_insertsort
#simple -c "extra" -m 65536 -M 65536 on2_selectsort
#simple -c "extra" -m 65536 -M 65536 on2_bubblesort
#simple -c "extra" -m 65536 -M 65536 on2_bubblesort2
#simple -c "extra" -m 65536 -M 65536 on2_shakersort
#simple -c "extra" -m 65536 -M 65536 on2_shakersort2

#simple -c "random.org" shellsort
#simple -c "random.org" old_shellsort

#simple -c "random.org" base_radixsort
#simple -c "random.org" cache_radixsort

#simple -c "random.org" base_heapsort
#simple -c "random.org" cache_heapsort
#simple -c "random.org" cache4_heapsort
#simple -c "16 byte random.org" -L 16 cache4_heapsort

#simple -c "random.org" base_quicksort
#simple -c "random.org" cache_quicksort
#simple -c "random.org" multi_quicksort
#simple -c "random.org" multi_quicksort_seq


#simple -c "random.org" base_mergesort
#simple -c "random.org" knuth_base_mergesort
#simple -c "random.org" knuth_other_base_mergesort
#simple -c "random.org" tiled_mergesort
simple -c "random.org" double_tiled_mergesort
#simple -c "random.org" multi_mergesort
simple -c "random.org" double_multi_mergesort
