#!/usr/bin/perl -w
$dir = "scripts";

opendir (SCRIPT_DIR, $dir);
@files = readdir(SCRIPT_DIR);
@files = grep {!/\.\./} @files;
@files = grep {!/\./} @files;
closedir SCRIPT_DIR;


foreach $file (@files)
{
	# open the file
	# read all the input
	open(FILE, $dir."/".$file) || die("cant read $file");
	@lines = <FILE>;
	close(FILE);
	
	# change it
	$lines[3] =~ s/4096,//g;
	$lines[3] =~ s/,4194304//g;
	$lines[8] =~ s/(..\/)*plots/..\/plots/g;
	$lines[5] =~ s/axis/x/g;
	for($i = 12; $i < scalar(@lines);$i++)
	{
		$lines[$i] =~ s/gnuplot_logs/..\/inputs/g;
	}

	# print it
	open(FILE, ">".$dir."/".$file) || die("cant write $file");
	print FILE @lines;
	close(FILE);

}

#chdir $dir;
#foreach $file (@files)
#{
#	@output = `gnuplot $file`;
#	foreach $out (@output)
#	{
#		print $out."\n";
#	}
#}
