#!/bin/sh

for ((  i = 0 ;  i < 1024;  i++  ))
do
# do the faster sorts first
	for j in algorithm_n algorithm_s aligned_memory_tuned_radixsort base_heapsort base_mergesort base_quicksort base_quicksort1 base_quicksort5 base_quicksort7 base_quicksort9 base_radixsort memory_tuned4_heapsort memory_tuned_heapsort memory_tuned_quicksort memory_tuned_radixsort do_nothing double_aligned_multi_mergsort double_aligned_mergesort improved_shellsort multi_mergesort multi_quicksort multi_quicksort_seq shellsort tiled_mergesort
	do
		for k in 4096 8192 16384 32768 65536 131072 262144 524288 1048576 2097152 4194304
		do
			./do_perfex $j $i $k
		done
	done 

# now do the on^2 sorts
	for j in insertsort selectsort bubblesort bubblesort2 shakersort shakersort2 
	do
		for k in 4096 8192 16384 32768 65536 131072
		do
			./do_perfex $j $i $k
		done
	done 

done
