#!/bin/bash

for ((  i = 0 ;  i < 10;  i++  ))
do

	for j in aligned_cache_radixsort base_heapsort base_mergesort base_quicksort base_quicksort1 base_quicksort5 base_quicksort7 base_quicksort9 base_radixsort cache4_heapsort cache_heapsort cache_quicksort cache_radixsort do_nothing double_multi_mergesort double_tiled_mergesort knuth_base_mergesort knuth_other_base_mergesort multi_mergesort multi_quicksort multi_quicksort_seq old_shellsort shellsort tiled_mergesort
	do
		./do_simple -c random.org$i -o $i $j
	done

	# do the 16 byte cache line heapsort
	./do_simple -c 16_byte_cache_line_random.org$i -o $i -L 16 cache4_heapsort

	for j in on2_insertsort on2_selectsort on2_bubblesort on2_bubblesort2 on2_shakersort on2_shakersort2 
	do
		./do_simple -c random.org$i -o $i -M 65536 $j 
	done
done
