#!/bin/sh

gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=$3 -DSEED=$2 -DSORT=$1 sorts/$1.c perfexMain.c -o $1
echo "$1-$3-$2"
papiex -u -q -e PAPI_TOT_CYC -e PAPI_L1_DCM -e PAPI_L2_TCM -e PAPI_BR_MSP ./$1 2>&1
