#!/bin/sh

gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=4096 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "4096-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=8192 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "8192-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=16384 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "16384-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=32768 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "32768-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=65536 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "65536-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=131072 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "131072-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=262144 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "262144-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=524288 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "524288-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=1048576 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "1048576-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=2097152 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "2097152-$1"
perfex $1
gcc -Wall -O3 -funroll-loops -finline-functions -DRANDOM_SIZE=4194304 -DSEED=0 -DSORT=$1 $1.c simpleMain.c -o $1
echo "4194304-$1"
perfex $1

rm $1
