#!/bin/sh

for i in 0 345 1234 9876 4567 84736 283764 384 20394 395 734 2684 3574 26845 235376 45
do
	do_perfex do_nothing $i

	do_perfex on2_insertsort $i
	do_perfex on2_selectsort $i
	do_perfex on2_bubblesort $i
	do_perfex on2_shakersort $i

	do_perfex base_heapsort $i
	do_perfex cache_heapsort $i
	do_perfex cache4_heapsort $i

	do_perfex base_quicksort $i
	do_perfex cache_quicksort $i
	do_perfex multi_quicksort $i
	do_perfex multi_quicksort_seq $i

	do_perfex base_radixsort $i

	do_perfex base_mergesort $i
	do_perfex knuth_base_mergesort $i
	do_perfex knuth_other_base_mergesort $i
	do_perfex tiled_mergesort $i
	do_perfex double_tiled_mergesort $i
	do_perfex multi_mergesort $i
	do_perfex double_multi_mergesort $i
done
